-- AlterTable
ALTER TABLE `itemdetail` ADD COLUMN `purchaseDate` DATETIME(3) NULL,
    MODIFY `status` ENUM('GUDANG', 'TERPASANG', 'RUSAK', 'TEKNISI', 'DI_OPERASIONAL_RUSUN_FTTH', 'DI_WAREHOUSE_GUDANG', 'DIOPERASIONAL_PERUMAHAN_FTTH', 'PINUS_LUAR', 'REPAIR', 'TERPASANG_DI_PERUMAHAN', 'TERPASANG_DI_RUSUN') NOT NULL DEFAULT 'GUDANG';

-- AlterTable
ALTER TABLE `itemhistory` MODIFY `action` ENUM('CREATE', 'UPDATE_STATUS', 'UPDATE_SN', 'UPDATE_MAC', 'UPDATE_NOTES', 'UPDATE_PURCHASE_DATE', 'UPDATE_LOCATION', 'DELETE', 'RESTORE', 'MOVE') NOT NULL;
